//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceiveDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductReceiveDetail()
        {
            this.ProductSaleOrderDetails = new HashSet<ProductSaleOrderDetail>();
            this.PurchaseProductReturns = new HashSet<PurchaseProductReturn>();
        }
    
        public long ProductReceiveDetailId { get; set; }
        public Nullable<long> ProductReceiveId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
        public Nullable<decimal> ReceiveUnitPrice { get; set; }
        public Nullable<double> EquvalentUMQty { get; set; }
        public Nullable<System.DateTime> EXPDate { get; set; }
        public Nullable<System.DateTime> MFGDate { get; set; }
        public Nullable<decimal> EquvalentPrice { get; set; }
        public Nullable<long> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual ProductReceive ProductReceive { get; set; }
        public virtual Product Product { get; set; }
        public virtual UOM UOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSaleOrderDetail> ProductSaleOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseProductReturn> PurchaseProductReturns { get; set; }
    }
}
