//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductReceiveDetails = new HashSet<ProductReceiveDetail>();
            this.ProductSaleDetails = new HashSet<ProductSaleDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.SaleOrderDetails = new HashSet<SaleOrderDetail>();
        }
    
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<decimal> MRPPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<long> LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpadateDateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceiveDetail> ProductReceiveDetails { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual UOM UOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSaleDetail> ProductSaleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; }
    }
}
