//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSaleOrder()
        {
            this.ProductSaleOrderDetails = new HashSet<ProductSaleOrderDetail>();
        }
    
        public long ProductSaleOrderId { get; set; }
        public Nullable<long> SaleOrderNo { get; set; }
        public Nullable<int> SaleSaleStatusId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string EntryBy { get; set; }
        public string EntryDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSaleOrderDetail> ProductSaleOrderDetails { get; set; }
        public virtual ProductSaleStatus ProductSaleStatus { get; set; }
    }
}
