//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSale()
        {
            this.ProductSaleDetails = new HashSet<ProductSaleDetail>();
        }
    
        public long ProductSaleId { get; set; }
        public Nullable<long> ProductSaleNo { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<long> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> SaleAmout { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string PaymentInfo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSaleDetail> ProductSaleDetails { get; set; }
    }
}
