//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductReceive()
        {
            this.ProductReceiveDetails = new HashSet<ProductReceiveDetail>();
        }
    
        public long ProductReceiveId { get; set; }
        public Nullable<long> PurchaseOrderId { get; set; }
        public string ReceiveNo { get; set; }
        public string ChalanOrLOtNo { get; set; }
        public Nullable<long> SupplierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReceiveDetail> ProductReceiveDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
