//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetail
    {
        public long SaleOrderDetailId { get; set; }
        public Nullable<long> SaleOrderId { get; set; }
        public Nullable<double> ProductQty { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<long> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
