//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProductReturn
    {
        public long ProductReturnId { get; set; }
        public Nullable<long> ProductSaleDetaisId { get; set; }
        public Nullable<double> ReturnRequestQty { get; set; }
        public Nullable<System.DateTime> ReturnRequestDate { get; set; }
        public string ReturnRequestBy { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<double> ReturnApproveQty { get; set; }
        public string ReturnApproveBy { get; set; }
        public Nullable<System.DateTime> ReturnApproveDate { get; set; }
    
        public virtual ProductSaleDetail ProductSaleDetail { get; set; }
    }
}
