//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreManagementDBEntities : DbContext
    {
        public StoreManagementDBEntities()
            : base("name=StoreManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<ProductReceiveDetail> ProductReceiveDetails { get; set; }
        public virtual DbSet<ProductReceive> ProductReceives { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSaleDetail> ProductSaleDetails { get; set; }
        public virtual DbSet<ProductSaleOrderDetail> ProductSaleOrderDetails { get; set; }
        public virtual DbSet<ProductSaleOrder> ProductSaleOrders { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<ProductSaleStatus> ProductSaleStatuses { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderStatus> PurchaseOrderStatuses { get; set; }
        public virtual DbSet<PurchaseProductReturn> PurchaseProductReturns { get; set; }
        public virtual DbSet<SaleOrderDetail> SaleOrderDetails { get; set; }
        public virtual DbSet<SaleOrder> SaleOrders { get; set; }
        public virtual DbSet<SaleOrderStatus> SaleOrderStatuses { get; set; }
        public virtual DbSet<SaleProductReturn> SaleProductReturns { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
    }
}
